apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  title: ${{ values.component_id }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.destination.owner }}/${{ values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - typescript
    - library
  links:
    - url: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}
      title: GitHub Repository
      icon: github
    - url: https://github.com/${{ values.destination.owner }}/${{ values.destination.repo }}/blob/main/docs/
      title: Documentation
      icon: docs
spec:
  type: library
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: developer-platform