name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: checkboxes
    id: preliminary
    attributes:
      label: Preliminary Checks
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have reproduced this issue in the latest version
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this bug?
      options:
        - Critical (System down, data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround available)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where was this bug encountered?
      options:
        - Production
        - Staging
        - Development
        - Local
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Screenshots
      description: If applicable, add error logs, console output, or screenshots
      placeholder: Paste logs or drag screenshots here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context here...

